[package]
authors = ["Maurice Kayser"]
edition = "2018"
keywords = ["ffi", "win32", "winapi", "windows"]
name = "winapi2"
version = "0.1.0"

[dependencies]
bitfield = { git = "https://github.com/MauriceKayser/rs-bitfield" }
from_primitive = { git = "https://github.com/MauriceKayser/rs-from-primitive" }